#front:
#    resource: "@FrontBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#easy_admin_bundle:
#    resource: "@EasyAdminBundle/Controller/AdminController.php"
#    type:     annotation
#    prefix:   /admin